server:
  port: 8083

spring:
  application:
    name: data-collector-service
  datasource:
    url: jdbc:mysql://localhost:3306/fault_warning_alert?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

influxdb:
  url: ${INFLUXDB_URL:http://localhost:8086}
  token: ${INFLUXDB_TOKEN:myDefaultInfluxDBTokenForDevelopment}
  org: ${INFLUXDB_ORG:cy}
  bucket: ${INFLUXDB_BUCKET:sensor_data}

ml:
  service:
    url: ${ML_SERVICE_URL:http://localhost:5000}

logging:
  level:
    com.example.datacollectorservice: DEBUG
    com.influxdb: DEBUG